/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                    "#b22204",
        "on-primary":                 "#ffffff",
        "primary-container":          "#d63c1e",
        "on-primary-container":       "#fffbff",
        "primary-fixed":              "#ffdad3",
        "primary-fixed-dim":          "#ffb4a4",
        "on-primary-fixed":           "#3e0500",
        "on-primary-fixed-variant":   "#8d1600",
        "inverse-primary":            "#ffb4a4",
        "secondary":                  "#7b5800",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#f9b500",
        "on-secondary-container":     "#684a00",
        "secondary-fixed":            "#ffdea6",
        "secondary-fixed-dim":        "#ffbb0c",
        "on-secondary-fixed":         "#271900",
        "on-secondary-fixed-variant": "#5d4200",
        "tertiary":                   "#00685c",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#008375",
        "on-tertiary-container":      "#f4fffb",
        "tertiary-fixed":             "#81f6e3",
        "tertiary-fixed-dim":         "#63dac7",
        "on-tertiary-fixed":          "#00201c",
        "on-tertiary-fixed-variant":  "#005047",
        "surface":                    "#f9f9f9",
        "surface-dim":                "#dadada",
        "surface-bright":             "#f9f9f9",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f3f3f3",
        "surface-container":          "#eeeeee",
        "surface-container-high":     "#e8e8e8",
        "surface-container-highest":  "#e2e2e2",
        "surface-variant":            "#e2e2e2",
        "surface-tint":               "#b62506",
        "on-surface":                 "#1a1c1c",
        "on-surface-variant":         "#5b403b",
        "inverse-surface":            "#2f3131",
        "inverse-on-surface":         "#f1f1f1",
        "outline":                    "#8f7069",
        "outline-variant":            "#e3beb6",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "background":                 "#f9f9f9",
        "on-background":              "#1a1c1c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        md:      "0.25rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.75rem",
        full:    "9999px",
      },
      spacing: {
        xs:              "4px",
        sm:              "8px",
        md:              "16px",
        lg:              "24px",
        gutter:          "10px",
        "margin-mobile": "12px",
        unit:            "4px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-md":  ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg":  ["16px", { lineHeight: "22px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "h1":       ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "h2":       ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "h3":       ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "price-lg": ["20px", { lineHeight: "20px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "caption":  ["10px", { lineHeight: "12px", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        bar:  "0 -2px 10px rgba(0,0,0,0.06)",
      },
    },
  },
  plugins: [],
};
